name: Ruins
version: ${project_version}
main: com.bins.ruins.Ruins
api-version: 1.16
depend: [ Kotlin, ProtocolLib, Citizens, WorldGuard, AutoUpdate ]
authors: [ A_bins, DDang_ ]
commands:
  인증:
  t:
  gun:
  stash:
  name:
    aliases: [ n, na, nam, 이름 ]
  lore:
    aliases: [ 로어 ]
  spawn:
    aliases: [ 넴주, 스폰, spawn, sp, spa, spaw, l, lo, lob, lobb, lobby, 로비 ]